/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.yjy.view;

import java.awt.Color;

/**
 *
 * @author Jemmy
 */
public class HalamanUtama extends javax.swing.JFrame {

    /**
     * Creates new form HalamanUtama
     */
    public HalamanUtama() {
        initComponents();
        redHome.setVisible(false);
        redExit.setVisible(false);
        redLogin.setVisible(false);
        redLogout.setVisible(false);
        meWhite.setVisible(false);
        txtArea.setBackground(new Color(0,0,0,60));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        greyHome = new javax.swing.JLabel();
        redHome = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        greyLogout = new javax.swing.JLabel();
        redLogout = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        greyLogin = new javax.swing.JLabel();
        redLogin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pg = new javax.swing.JLabel();
        hg = new javax.swing.JLabel();
        rg = new javax.swing.JLabel();
        mg = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        meBlack = new javax.swing.JLabel();
        meWhite = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        greyExit = new javax.swing.JLabel();
        redExit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        greyHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/Home-WF.png"))); // NOI18N
        jPanel2.add(greyHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        redHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/Home-WF01.png"))); // NOI18N
        jPanel2.add(redHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 60, 60));

        jPanel4.setOpaque(false);
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        greyLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/Logout-WF.png"))); // NOI18N
        jPanel4.add(greyLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        redLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/Logout-WF01.png"))); // NOI18N
        jPanel4.add(redLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, 60, 60));

        jPanel5.setOpaque(false);
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        greyLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/Login Door1-WF.png"))); // NOI18N
        jPanel5.add(greyLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        redLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/Login Door01-WF.png"))); // NOI18N
        jPanel5.add(redLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 60, 60));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Let's Explore");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        pg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/pg.png"))); // NOI18N
        pg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pgMouseClicked(evt);
            }
        });
        jPanel1.add(pg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 70, 40));

        hg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/hg.png"))); // NOI18N
        hg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hgMouseClicked(evt);
            }
        });
        jPanel1.add(hg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 70, 40));

        rg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/rg.png"))); // NOI18N
        rg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rgMouseClicked(evt);
            }
        });
        jPanel1.add(rg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 70, 40));

        mg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/mg.png"))); // NOI18N
        mg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mgMouseClicked(evt);
            }
        });
        jPanel1.add(mg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 70, 40));

        jPanel6.setOpaque(false);
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        meBlack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/AboutMe.png"))); // NOI18N
        jPanel6.add(meBlack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        meWhite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/AboutMe01.png"))); // NOI18N
        jPanel6.add(meWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 70, 70));

        jPanel7.setOpaque(false);
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        greyExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/Shutdown-WF01.png"))); // NOI18N
        jPanel7.add(greyExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        redExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/Shutdown-WF.png"))); // NOI18N
        jPanel7.add(redExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, 60, 60));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/HalamanUtamaKiri.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 500));

        txtArea.setEditable(false);
        txtArea.setBackground(new java.awt.Color(0, 0, 0));
        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        txtArea.setForeground(new java.awt.Color(255, 255, 255));
        txtArea.setRows(5);
        txtArea.setText("Gunpla adalah salah satu action model berdasarkan \nGundam Series, gunpla ini membutuhkan penyusunan agar\ndapat dinikmati dengan optimal.\nBanyak gunpla builder yang senang mengkoleksi gunpla, \nbukan hanya karena hasil akhir yang keren, tapi juga\nsensasi saat menyusun gunpla yang dibilang cukup rumit.\nBukan hanya karena tidak disediakannya panduan berbahasa lain \nselain Jepang, tapi banyaknya teknik untuk meningkatkan kedetailan\ngunpla tersebut.\nGunpla sendiri memiliki levelnya masing - masing,\\\ndimulai dari HG (High Grade), RG(Real Grade), MG(Master Grade) \nhingga PG(Perfect Grade) yang detailnya meningkat\nsetiap grade yang diambil meninggkat");
        txtArea.setBorder(null);
        jPanel1.add(txtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/gunplaLogo.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 450, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/HalamanUtamaBackground.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 0, 1090, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
        redHome.setVisible(true);
        greyHome.setVisible(false);
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        // TODO add your handling code here:
        greyHome.setVisible(true);
        redHome.setVisible(false);
    }//GEN-LAST:event_jPanel2MouseExited

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        // TODO add your handling code here:
        redLogout.setVisible(true);
        greyLogout.setVisible(false);
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        // TODO add your handling code here:
        redLogout.setVisible(false);
        greyLogout.setVisible(true);
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        // TODO add your handling code
        redLogin.setVisible(true);
        greyLogin.setVisible(false);
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        // TODO add your handling code here:
        redLogin.setVisible(false);
        greyLogin.setVisible(true);
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        LoginMenu login = new LoginMenu();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        LoginMenu login = new LoginMenu();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        HalamanUtama utama = new HalamanUtama();
        this.setVisible(false);
        utama.setVisible(true);
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        // TODO add your handling code here:
        meWhite.setVisible(true);
        meBlack.setVisible(false);
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        // TODO add your handling code here:
        meWhite.setVisible(false);
        meBlack.setVisible(true);
    }//GEN-LAST:event_jPanel6MouseExited

    private void hgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hgMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        HGmenu oHG = new HGmenu();
        oHG.setVisible(true);
    }//GEN-LAST:event_hgMouseClicked

    private void rgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rgMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        RGmenu oRG = new RGmenu();
        oRG.setVisible(true);
    }//GEN-LAST:event_rgMouseClicked

    private void mgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mgMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        MGmenu oMG = new MGmenu();
        oMG.setVisible(true);
    }//GEN-LAST:event_mgMouseClicked

    private void pgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pgMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        PGmenu oPG = new PGmenu();
        oPG.setVisible(true);
    }//GEN-LAST:event_pgMouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
        // TODO add your handling code here:
        redExit.setVisible(true);
        greyExit.setVisible(false);
    }//GEN-LAST:event_jPanel7MouseEntered

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited
        // TODO add your handling code here:
        redExit.setVisible(false);
        greyExit.setVisible(true);
    }//GEN-LAST:event_jPanel7MouseExited

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        About about = new About();
        about.setVisible(true);
    }//GEN-LAST:event_jPanel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel greyExit;
    private javax.swing.JLabel greyHome;
    private javax.swing.JLabel greyLogin;
    private javax.swing.JLabel greyLogout;
    private javax.swing.JLabel hg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel meBlack;
    private javax.swing.JLabel meWhite;
    private javax.swing.JLabel mg;
    private javax.swing.JLabel pg;
    private javax.swing.JLabel redExit;
    private javax.swing.JLabel redHome;
    private javax.swing.JLabel redLogin;
    private javax.swing.JLabel redLogout;
    private javax.swing.JLabel rg;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
