/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.yjy.view;

/**
 *
 * @author Jemmy
 */
public class PGmenu extends javax.swing.JFrame {

    /**
     * Creates new form PGmenu
     */
    public PGmenu() {
        initComponents();
        redHome.setVisible(false);
        redExit.setVisible(false);
        A2.setVisible(false);
        B2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        A1 = new javax.swing.JLabel();
        A2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        B1 = new javax.swing.JLabel();
        B2 = new javax.swing.JLabel();
        hg = new javax.swing.JLabel();
        rg = new javax.swing.JLabel();
        mg = new javax.swing.JLabel();
        pg = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        greyHome = new javax.swing.JLabel();
        redHome = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        greyExit = new javax.swing.JLabel();
        redExit = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        meBlack = new javax.swing.JLabel();
        meWhite = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Let's Explore");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        A1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/pgA1.png"))); // NOI18N
        jPanel2.add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        A2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/pgA2.png"))); // NOI18N
        jPanel2.add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 350));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 250, 350));

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/pgB1.png"))); // NOI18N
        jPanel3.add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 350));

        B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/pgB2.png"))); // NOI18N
        jPanel3.add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 250, 350));

        hg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/hg.png"))); // NOI18N
        hg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hgMouseClicked(evt);
            }
        });
        jPanel1.add(hg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 70, 40));

        rg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/rg.png"))); // NOI18N
        rg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rgMouseClicked(evt);
            }
        });
        jPanel1.add(rg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 70, 40));

        mg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/mg.png"))); // NOI18N
        mg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mgMouseClicked(evt);
            }
        });
        jPanel1.add(mg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 70, 40));

        pg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/pg.png"))); // NOI18N
        pg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pgMouseClicked(evt);
            }
        });
        jPanel1.add(pg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 70, 40));

        jPanel7.setOpaque(false);
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        greyHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/Home-WF.png"))); // NOI18N
        jPanel7.add(greyHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        redHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/Home-WF01.png"))); // NOI18N
        jPanel7.add(redHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 60, 60));

        jPanel8.setOpaque(false);
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel8MouseExited(evt);
            }
        });
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        greyExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/Shutdown-WF01.png"))); // NOI18N
        jPanel8.add(greyExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        redExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/Shutdown-WF.png"))); // NOI18N
        jPanel8.add(redExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, 60, 60));

        jPanel6.setOpaque(false);
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        meBlack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/AboutMe.png"))); // NOI18N
        jPanel6.add(meBlack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        meWhite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/AboutMe01.png"))); // NOI18N
        jPanel6.add(meWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 70, 70));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/HalamanUtamaKiri.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/yjy/asset/BackgorundMenu.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
        A1.setVisible(false);
        A2.setVisible(true);
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        // TODO add your handling code here:
        A2.setVisible(false);
        A1.setVisible(true);
    }//GEN-LAST:event_jPanel2MouseExited

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
        B2.setVisible(true);
        B1.setVisible(false);
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:
        B2.setVisible(false);
        B1.setVisible(true);
    }//GEN-LAST:event_jPanel3MouseExited

    private void hgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hgMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        HGmenu oHG = new HGmenu();
        oHG.setVisible(true);
    }//GEN-LAST:event_hgMouseClicked

    private void rgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rgMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        RGmenu oRG = new RGmenu();
        oRG.setVisible(true);
    }//GEN-LAST:event_rgMouseClicked

    private void mgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mgMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        MGmenu oMG = new MGmenu();
        oMG.setVisible(true);
    }//GEN-LAST:event_mgMouseClicked

    private void pgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pgMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        PGmenu oPG = new PGmenu();
        oPG.setVisible(true);
    }//GEN-LAST:event_pgMouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // TODO add your handling code here:
        HalamanUtama utama = new HalamanUtama();
        this.setVisible(false);
        utama.setVisible(true);
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
        // TODO add your handling code here:
        redHome.setVisible(true);
        greyHome.setVisible(false);
    }//GEN-LAST:event_jPanel7MouseEntered

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited
        // TODO add your handling code here:
        greyHome.setVisible(true);
        redHome.setVisible(false);
    }//GEN-LAST:event_jPanel7MouseExited

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseEntered
        // TODO add your handling code here:
        redExit.setVisible(true);
        greyExit.setVisible(false);
    }//GEN-LAST:event_jPanel8MouseEntered

    private void jPanel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseExited
        // TODO add your handling code here:
        redExit.setVisible(false);
        greyExit.setVisible(true);
    }//GEN-LAST:event_jPanel8MouseExited

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        About about = new About();
        about.setVisible(true);
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        // TODO add your handling code here:
        meWhite.setVisible(true);
        meBlack.setVisible(false);
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        // TODO add your handling code here:
        meWhite.setVisible(false);
        meBlack.setVisible(true);
    }//GEN-LAST:event_jPanel6MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PGmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PGmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PGmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PGmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PGmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A1;
    private javax.swing.JLabel A2;
    private javax.swing.JLabel B1;
    private javax.swing.JLabel B2;
    private javax.swing.JLabel greyExit;
    private javax.swing.JLabel greyHome;
    private javax.swing.JLabel hg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel meBlack;
    private javax.swing.JLabel meWhite;
    private javax.swing.JLabel mg;
    private javax.swing.JLabel pg;
    private javax.swing.JLabel redExit;
    private javax.swing.JLabel redHome;
    private javax.swing.JLabel rg;
    // End of variables declaration//GEN-END:variables
}
